# Generated by Django 5.2.15 on 2026-06-14 01:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant demandé (FCFA)')),
                ('taux_interet', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name="Taux d'intérêt (%)")),
                ('duree_mois', models.PositiveIntegerField(verbose_name='Durée (mois)')),
                ('frequence', models.CharField(choices=[('HEBDO', 'Hebdomadaire'), ('MENSUEL', 'Mensuelle')], default='MENSUEL', max_length=10, verbose_name='Fréquence')),
                ('objet', models.CharField(choices=[('COMMERCE', 'Commerce / Négoce'), ('AGRICULTURE', 'Agriculture'), ('ARTISANAT', 'Artisanat'), ('SANTE', 'Frais de santé'), ('EDUCATION', 'Scolarité / Formation'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name='Objet du crédit')),
                ('taux_penalite', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5, verbose_name='Taux pénalité/jour (%)')),
                ('statut', models.CharField(choices=[('SOUMISE', 'Soumise'), ('EN_ANALYSE', 'En analyse'), ('APPROUVEE', 'Approuvée'), ('DECAISSEE', 'Décaissée'), ('REJETEE', 'Rejetée'), ('CLOTUREE', 'Clôturée / Soldée')], default='SOUMISE', max_length=20, verbose_name='Statut')),
                ('score_eligibilite', models.PositiveIntegerField(blank=True, null=True, verbose_name='Score éligibilité (0-100)')),
                ('date_demande', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('date_decision', models.DateField(blank=True, null=True, verbose_name='Date décision')),
                ('date_decaissement', models.DateField(blank=True, null=True, verbose_name='Date de décaissement')),
                ('motif_rejet', models.TextField(blank=True, verbose_name='Motif de rejet')),
            ],
            options={
                'verbose_name': 'Crédit',
                'verbose_name_plural': 'Crédits',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_doc', models.CharField(choices=[('CNI', "Carte Nationale d'Identité"), ('JUSTIF_REVENU', 'Justificatif de revenu'), ('ATTESTATION', 'Attestation de résidence'), ('PHOTO', "Photo d'identité"), ('AUTRE', 'Autre document')], default='AUTRE', max_length=20)),
                ('fichier', models.FileField(upload_to='documents/credits/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.CreateModel(
            name='Echeancier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='N° échéance')),
                ('date_echeance', models.DateField(verbose_name="Date d'échéance")),
                ('montant_du', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant dû (FCFA)')),
                ('statut', models.CharField(choices=[('A_PAYER', 'À payer'), ('PARTIELLEMENT_PAYE', 'Partiellement payé'), ('PAYE', 'Payé'), ('EN_RETARD', 'En retard')], default='A_PAYER', max_length=25, verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Échéancier',
                'verbose_name_plural': 'Échéanciers',
                'ordering': ['credit', 'numero'],
            },
        ),
    ]
