# Generated by Django 5.2.15 on 2026-06-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='id_document_recto',
            field=models.FileField(blank=True, null=True, upload_to='ids/', verbose_name="Pièce d'identité (Recto)"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='id_document_verso',
            field=models.FileField(blank=True, null=True, upload_to='ids/', verbose_name="Pièce d'identité (Verso)"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name="Numéro de pièce d'identité"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='id_type',
            field=models.CharField(choices=[('CNI', "Carte Nationale d'Identité"), ('PASSEPORT', 'Passeport'), ('ATTESTATION', "Attestation d'identité")], default='CNI', max_length=30, verbose_name="Type de pièce d'identité"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name="Photo d'identité"),
        ),
    ]
