# Generated by Django 5.2.15 on 2026-06-14 01:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitAssurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, verbose_name='Nom du produit')),
                ('categorie', models.CharField(choices=[('VIE', 'Assurance Vie'), ('DECES_INVALIDITE', 'Décès-Invalidité'), ('SANTE', 'Santé / Hospitalisation'), ('ACCIDENT', 'Accident'), ('MULTIRISQUE', 'Multirisque')], default='VIE', max_length=20)),
                ('description', models.TextField(verbose_name='Description')),
                ('prime_mensuelle', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prime mensuelle (FCFA)')),
                ('duree_validite_mois', models.PositiveIntegerField(default=12, verbose_name='Durée de validité (mois)')),
                ('couverture_max', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Couverture maximale (FCFA)')),
                ('actif', models.BooleanField(default=True, verbose_name='Produit actif')),
            ],
            options={
                'verbose_name': "Produit d'assurance",
                'verbose_name_plural': "Produits d'assurance",
                'ordering': ['categorie', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='SouscriptionAssurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(default=django.utils.timezone.now, verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIREE', 'Expirée'), ('RESILIEE', 'Résiliée')], default='ACTIVE', max_length=15)),
                ('alerte_expiration_envoyee', models.BooleanField(default=False, verbose_name='Alerte J-15 envoyée')),
            ],
            options={
                'verbose_name': 'Souscription assurance',
                'verbose_name_plural': 'Souscriptions assurance',
                'ordering': ['-date_debut'],
            },
        ),
    ]
