# Generated by Django 5.2.15 on 2026-06-10 20:01

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitAssurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('tarif_mensuel', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('CLIENT', 'Client'), ('AGENT', 'Agent de terrain'), ('ADMIN', 'Administrateur')], default='CLIENT', max_length=15)),
                ('telephone', models.CharField(help_text='Numéro utilisé pour le Mobile Money', max_length=20, unique=True)),
                ('region', models.CharField(blank=True, choices=[('ABIDJAN', 'Abidjan'), ('BOUAKE', 'Bouaké'), ('KORHOGO', 'Korhogo'), ('YAMOUSSOUKRO', 'Yamoussoukro'), ('SAN_PEDRO', 'San Pédro')], max_length=30, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('FERMEE', 'Fermée')], default='OUVERTE', max_length=15)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations_agent', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, help_text='Montant du crédit en FCFA', max_digits=12)),
                ('taux_interet', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text="Taux d'intérêt annuel ou mensuel en %", max_digits=5)),
                ('duree_mois', models.PositiveIntegerField(help_text='Durée du remboursement en mois')),
                ('taux_penalite', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Taux de pénalité de retard par jour en %', max_digits=5)),
                ('statut', models.CharField(choices=[('SOUMISE', 'Soumise'), ('EN_ANALYSE', 'En analyse'), ('APPROUVEE', 'Approuvée'), ('DECAISSEE', 'Décaissée'), ('REJETEE', 'Rejetée'), ('CLOTUREE', 'Clôturée / Soldée')], default='SOUMISE', max_length=20)),
                ('score_eligibilite', models.PositiveIntegerField(blank=True, help_text="Score d'éligibilité calculé automatiquement de 0 à 100", null=True)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credits_demandes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Echeancier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_echeance', models.DateField()),
                ('montant_du', models.DecimalField(decimal_places=2, max_digits=12)),
                ('statut', models.CharField(choices=[('A_PAYER', 'À payer'), ('PAYE', 'Payé'), ('EN_RETARD', 'En retard')], default='A_PAYER', max_length=15)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeances', to='core.credit')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('envoye_le', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.conversation')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('type_notification', models.CharField(choices=[('CHANGEMENT_STATUT_CREDIT', 'Changement statut crédit'), ('RAPPEL_ECHEANCE_REMBOUSEMENT', 'Rappel échéance remboursement'), ('EXPIRATION_ASSURANCE', 'Expiration assurance imminent')], max_length=50)),
                ('lu', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital_paye', models.DecimalField(decimal_places=2, help_text="Partie du paiement allouée au capital de l'échéance", max_digits=12)),
                ('penalites_payees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Pénalités de retard payées en plus', max_digits=10)),
                ('mode_paiement', models.CharField(choices=[('ORANGE_MONEY', 'Orange Money'), ('WAVE', 'Wave'), ('MTN_MOMO', 'MTN MoMo'), ('ESPECES', 'Espèces')], default='ESPECES', max_length=20)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('echeancier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='core.echeancier')),
                ('enregistre_par', models.ForeignKey(limit_choices_to={'role': 'AGENT'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PieceJustificative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='justificatifs/')),
                ('nom_piece', models.CharField(help_text="Ex: Pièce d'identité, Justificatif de domicile", max_length=100)),
                ('charge_le', models.DateTimeField(auto_now_add=True)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='core.credit')),
            ],
        ),
        migrations.CreateModel(
            name='SouscriptionAssurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIREE', 'Expirée'), ('RESILIEE', 'Résiliée')], default='ACTIVE', max_length=15)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assurances_souscrites', to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.produitassurance')),
            ],
        ),
    ]
