# Generated by Django 5.2.15 on 2026-06-14 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('FERMEE', 'Fermée')], default='OUVERTE', max_length=10)),
                ('sujet', models.CharField(blank=True, max_length=200, verbose_name='Sujet')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('ferme_le', models.DateTimeField(blank=True, null=True, verbose_name='Fermée le')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('envoye_le', models.DateTimeField(auto_now_add=True, verbose_name='Envoyé le')),
                ('lu_par_agent', models.BooleanField(default=False)),
                ('lu_par_client', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['envoye_le'],
            },
        ),
    ]
