# Generated by Django 5.2.15 on 2026-06-14 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital_paye', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Capital payé (FCFA)')),
                ('penalites_payees', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Pénalités payées (FCFA)')),
                ('mode_paiement', models.CharField(choices=[('WAVE', 'Wave'), ('ORANGE_MONEY', 'Orange Money'), ('MTN_MOMO', 'MTN MoMo'), ('ESPECES', 'Espèces')], default='ESPECES', max_length=20, verbose_name='Mode de paiement')),
                ('reference_transaction', models.CharField(blank=True, max_length=100, verbose_name='Référence transaction Mobile Money')),
                ('date_paiement', models.DateTimeField(auto_now_add=True, verbose_name='Date de paiement')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('echeancier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='credits.echeancier', verbose_name='Échéance')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
    ]
