# Generated by Django 5.2.15 on 2026-06-14 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('type_notif', models.CharField(choices=[('CREDIT', 'Crédit'), ('REMBOURSEMENT', 'Remboursement'), ('ASSURANCE', 'Assurance'), ('ALERTE', 'Alerte'), ('SYSTEME', 'Système')], default='SYSTEME', max_length=20, verbose_name='Type')),
                ('lu', models.BooleanField(default=False, verbose_name='Lu')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-cree_le'],
            },
        ),
    ]
